name: interactsmi_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.6.0
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - ipykernel
  - pymol-open-source
  - openbabel
  - rdkit
  - numpy
  - h5py
  - scipy
  - scikit-learn